name: Deploy Shiny App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TOKEN_GOOGLESHEETS_ZOOTRAITS: ${{ secrets.TOKEN_GOOGLESHEETS_ZOOTRAITS }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'
          use-public-rspm: false


      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::rsconnect
            any::remotes

      - name: Install zootraits and rsconnect
        run: |
          remotes::install_github("thiago-goncalves-souza/zootraits")
          install.packages("rsconnect", repos = "https://cran.rstudio.com")

        shell: Rscript {0}

      - name: Write service account key to file
        run: echo "${{ secrets.TOKEN_GOOGLESHEETS_ZOOTRAITS }}" > inst/token.json

      - name: Set up rsconnect account
        run: |
          rsconnect::setAccountInfo(
            name = "ecofun",
            token = "${{ secrets.SHINYAPPS_TOKEN }}",
            secret = "${{ secrets.SHINYAPPS_SECRET }}"
          )
        shell: Rscript {0}

      - name: Deploy Shiny App
        run: |
          rsconnect::deployApp(
            appDir = ".",
            appName = "zootraits",
            account = "ecofun"
          )
        shell: Rscript {0}
