name: Deploy Shiny App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'
          use-public-rspm: true


      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::rsconnect
            any::giscoR
            any::viridis
            any::cpp11
            any::plogr
            any::progress
            any::geometries
            any::jsonify
            any::rapidjsonr
            any::sfheaders

      - name: Install zootraits from GitHub
        run: |
          install.packages("remotes")
          remotes::install_github("thiago-goncalves-souza/zootraits")
        shell: Rscript {0}


      - name: Set up rsconnect account
        run: |
          rsconnect::setAccountInfo(
            name = "ecofun",
            token = "${{ secrets.SHINYAPPS_TOKEN }}",
            secret = "${{ secrets.SHINYAPPS_SECRET }}"
          )
        shell: Rscript {0}

      - name: Deploy Shiny App
        run: |
          options(rsconnect.packrat.enabled = FALSE)
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          rsconnect::deployApp(
            appDir = ".",
            appName = "zootraits",
            account = "ecofun"
          )
        shell: Rscript {0}
